### ISSUE TITLE
homework 調整

### ISSUE THREAD

**Issue by hatelove** [tsengeagle/TDD_develop#1]
在測試程式中，底下這一行
List<int> inputList = sourceList.Select(s => s.Cost).ToList();
代表呼叫端要用 production code 的 API 之前，「呼叫端得自己先把要篩選的欄位過濾出來」，這樣就代表這個 API 不夠好用，因為你把篩選欄位的商業邏輯，交給了呼叫端自己控制。

請改成傳欄位名稱進去，production code 就可以自動幫忙篩選該欄位的分組加總結果。

**Comment by tsengeagle** [comment]
新增測試案例確保欄位亂傳的時候程式不會壞掉
